steps:
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: API_KEY=$(
      args:
        - 'gcloud'
        - 'secrets'	
        - 'versions'	
        - 'access'	
        - 'latest'	
        - '--secret=API_KEY)'
    - name: bash
      args:
        - 'echo $API_KEY'
    - name: maven:3-jdk-8
      entrypoint: mvn
      args:
        - 'clean'
        - 'package'
        - 'appengine:deploy'
        - '-Dmaven.test.skip=true'
        - '-Dapp.deploy.promote=False'
        - '-Dapp.deploy.version=$_PR_NUMBER'
        - '-Dapp.deploy.projectId=$PROJECT_ID'
        - '-DAPI_KEY=${API_KEY}'
