steps:
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: bash
      args:
        - echo ${_API_KEY}
      env:
        - '_API_KEY=$(gcloud secrets versions access latest --secret=API_KEY)'
    - name: maven:3-jdk-8
      entrypoint: mvn
      args:
        - 'clean'
        - 'package'
        - 'appengine:deploy'
        - '-Dmaven.test.skip=true'
        - '-Dapp.deploy.promote=False'
        - '-Dapp.deploy.version=$_PR_NUMBER'
        - '-Dapp.deploy.projectId=$PROJECT_ID'
