steps:
    - name: node:10.15.1
      entrypoint: npm
      args: ["install"]
    - name: node:10.15.1
      entrypoint: npm
      args: ["run", "create-env"]
      env:
        - 'API_KEY=${_API_KEY}'
    - name: echo
      entrypoint: bash
      args:
        - 'echo $API_KEY'
    - name: maven:3-jdk-8
      entrypoint: mvn
      args:
        - 'clean'
        - 'package'
        - 'appengine:deploy'
        - '-Dmaven.test.skip=true'
        - '-Dapp.deploy.promote=False'
        - '-Dapp.deploy.version=$_PR_NUMBER'
        - '-Dapp.deploy.projectId=$PROJECT_ID'
