extends: ["eslint:recommended", "google"]
env:
  es6: true
  browser: true
"parserOptions": {
  "ecmaVersion": 2017
}
"rules": {
  "comma-dangle": ["error", {
    "arrays": "always",
    "objects": "always",
    "imports": "never",
    "exports": "never",
    "functions": "never"
  }]
}
